### ISSUE TITLE
Can you help me get the pose using topics (/ground_truth/state) and (/altimeter or /ardrone/navdata)

### ISSUE THREAD

**Issue by wajeehulhassanvii** [eborghi10/AR.Drone-ROS#3]
Hi @eborghi10 I want to get the pose of the drone, like /drone/gt_pose in parrot drone. Since I am new to ROS thats why I am finding it difficult to implement the code myself. It'd be wonderful if you could share me the details about implementing it. Thanks

**Comment by eborghi10** [comment]
Could you start the simulation? Create a [workspace](http://wiki.ros.org/catkin/Tutorials/create_a_workspace)? A [package](http://wiki.ros.org/ROS/Tutorials/CreatingPackage)?

In order to get this work, you will need to [subscribe to the topics](http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28python%29) and fill a [pose message](http://docs.ros.org/api/geometry_msgs/html/msg/Pose.html). [This is an example of how to fill a message](http://wiki.ros.org/ROS/Tutorials/CustomMessagePublisherSubscriber%28python%29).

**Comment by wajeehulhassanvii** [comment]
I got it working, created a Ros node which publishes **Pose** in /get_pose topic, and I can echo the topic to get the Pose of the drone too.
Thanks @eborghi10 , I appreciate for taking out the time for helping me :)

**Comment by eborghi10** [comment]
I'm glad you could solve it. If you want, please create a PR with your changes. Thanks!

**Comment by wajeehulhassanvii** [comment]
I want to push the changes but I have created another package and a node to implement '/get_pose' topic. Is it okay if I push it?

**Comment by wajeehulhassanvii** [comment]
I'm using this code for publishing pose. Do you think its okay?

```

#! /usr/bin/env python

import rospy
from geometry_msgs.msg import Twist, Vector3Stamped, Pose
from std_msgs.msg import Header
from gazebo_msgs.srv import GetModelState, GetModelStateRequest, GetLinkState, GetLinkStateRequest
from sensor_msgs.msg import Imu

rospy.init_node('get_pose_topic')

my_pub = rospy.Publisher('/get_pose'
                        , Pose
                        , queue_size=10
                        )

rospy.wait_for_service('/gazebo/get_link_state')
get_link_state=rospy.ServiceProxy('/gazebo/get_link_state', GetLinkState)

my_pose = Pose()

link = GetLinkStateRequest()
link_name='quadrotor::base_link'

#r = rospy.Rate(1000)
#r = rospy.Rate(1)

while not rospy.is_shutdown():

    res_link_state = get_link_state(link_name, None)
    my_pose = res_link_state.link_state.pose
    my_pub.publish(my_pose)

```

**Comment by eborghi10** [comment]
I recommend you to follow these steps @wajeehulhassanvii :

- [Fork this repository](https://help.github.com/en/articles/fork-a-repo). This will create a copy for you where you can make changes and test it.
- Once there, clone it to you local computer and create the ROS package.
- Inside this ROS package, create a [ROS launch file](http://www.clearpathrobotics.com/assets/guides/ros/Launch%20Files.html) that runs the whole simulation along with your new node.
- Push your changes **to your fork** and you'll be able to see in this repo the option to create a pull request.
- Once you create the PR, I'll take a look at your code because it's easier.

If you don't feel very comfortable working with Git, I strongly suggest you to do this [Udacity course](https://www.udacity.com/course/github-collaboration--ud456).

**Comment by wajeehulhassanvii** [comment]
Okay I'll have a look, I understand Git a bit so it wouldn't be a problem hopefully.
